# 当接收到的群消息或好友消息为 hello 或「你好」时回复「Hello World!（你好 世界！）」
global:
  - when:
      message:
        - type: Plain
          text: hello
        - type: Plain
          text: 你好
    do:
      message:
        - type: Plain
          text: Hello World!
        - type: Plain
          text: （你好 世界！）

group:
# 当接收到的群消息为 say 时，调用「一言API」，原文发送接口返回的消息
  - when:
      message:
        - type: Plain
          text: say
    do:
      message:
        - type: Plain
          url: https://v1.hitokoto.cn?encode=text

# 当接收到的群消息为 jsay 时，调用「一言API」，解析返回后数据并拼接成文本消息发送
  - when:
      message:
        - type: Plain
          text: jsay
    do:
      message:
        - type: Plain
          url: https://v1.hitokoto.cn?encode=json&charset=utf-8
          jtext: '{hitokoto} ——— {from}'
  - when:
      operation:
        - type: MuteMember
    do:
      message:
        - type: Plain
          text: 有人被禁言啦！！！
  - when:
      operation:
        - type: MemberUnmute
    do:
      message:
        - type: Plain
          text: 恭喜出狱
  - when:
      operation:
        - type: GroupMuteAll
    do:
      message:
        - type: Plain
          text: 砸瓦鲁多！

  - when:
      operation:
        - type: GroupUnMuteAll
    do:
      message:
        - type: Plain
          text: 隐藏着黑暗力量的钥匙啊,在我面前显示你真正的力量！现在以你的主人，小樱之名命令你。封印解除！
  
  - when:
      operation:
        - type: MemberJoin
    do:
      message:
        - type: Plain
          text: 新人进群，群地位-1。
