# 当接收到的群消息或好友消息为 hello 或「你好」时回复「Hello World!（你好 世界！）」
global:
  - when:
      message:
        - type: Plain
          text: hello
        - type: Plain
          text: 你好
    do:
      message:
        - type: Plain
          text: Hello World!
        - type: Plain
          text: （你好 世界！）

group:
# 当接收到的群消息为 say 时，调用「一言API」，原文发送接口返回的消息
  - when:
      message:
        - type: Plain
          text: say
    do:
      message:
        - type: Plain
          url: https://v1.hitokoto.cn?encode=text

# 当接收到的群消息为 jsay 时，调用「一言API」，解析返回后数据并拼接成文本消息发送
  - when:
      message:
        - type: Plain
          text: jsay
    do:
      message:
        - type: Plain
          url: https://v1.hitokoto.cn?encode=json&charset=utf-8
          jtext: '{hitokoto} ——— {from}'
  - when:
      operation:
        - type: MuteMember
    do:
      message:
        - type: Plain
          text: 有人被禁言啦！！！
  - when:
      operation:
        - type: MemberUnmute
    do:
      message:
        - type: Plain
          text: 恭喜出狱