# 请勿改动此文件

weixiao: 14
piezui: 1
se: 2
fadai: 3
deyi: 4
liulei: 5
haixiu: 6
bizui: 7
shui: 8
daku: 9
ganga: 10
fanu: 11
tiaopi: 12
ciya: 13
jingya: 0
nanguo: 15
ku: 16
lenghan: 96
zhuakuang: 18
tu: 19
touxiao: 20
keai: 21
baiyan: 22
aoman: 23
ji_e: 24
kun: 25
jingkong: 26
liuhan: 27
hanxiao: 28
dabing: 29
fendou: 30
zhouma: 31
yiwen: 32
yun: 34
zhemo: 35
shuai: 36
kulou: 37
qiaoda: 38
zaijian: 39
cahan: 97
koubi: 98
guzhang: 99
qiudale: 100
huaixiao: 101
zuohengheng: 102
youhengheng: 103
haqian: 104
bishi: 105
weiqu: 106
kuaikule: 107
yinxian: 108
qinqin: 109
xia: 110
kelian: 111
caidao: 112
xigua: 89
pijiu: 113
lanqiu: 114
pingpang: 115
kafei: 60
fan: 61
zhutou: 46
meigui: 63
diaoxie: 64
shiai: 116
aixin: 66
xinsui: 67
dan_gao: 53
shandian: 54
zhadan: 55
dao: 56
qidao: 145
zuqiu: 57
piaochong: 117
bianbian: 59
yueliang: 75
taiyang: 74
liwu: 69
yongbao: 49
qiang: 76
ruo: 77
woshou: 78
shengli: 79
baoquan: 118
gouyin: 119
quantou: 120
chajin: 121
aini: 122
bu: 123
hao: 124
aiqing: 42
feiwen: 85
tiaotiao: 43
fadou: 41
naohuo: 86
zhuanquan: 125
ketou: 126
huitou: 127
tiaosheng: 128
huishou: 129
jidong: 130
jiewu: 131
xianwen: 132
zuotaiji: 133
youtaiji: 134
shuangxi: 136
bianpao: 137
denglong: 138
K_ge: 140
hecai: 144
baojin: 146
bangbangtang: 147
he_nai: 148
feiji: 151
chaopiao: 158
yao: 168
shouqiang: 169
dan: 188
hongbao: 192
hexie: 184
yangtuo: 185
juhua: 190
youling: 187
daxiao: 193
bukaixin: 194
lengmo: 197
e: 198
haobang: 199
baituo: 200
dianzan: 201
wuliao: 202
tuolian: 203
chi: 204
songhua: 205
haipa: 206
xiaoyanger: 208
biaolei: 210
wobukan: 211